language: node_js
node_js: lts/*
cache:
  npm: false
before_script: 
script:
- yarn install
- yarn build
deploy:
  local_dir: ".vuepress/dist/"
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  github_token:
    secure: bIEQ6X9OsGytHgaNWOFvENDfM44yUO2c7ibqmirRj359QMsF6ASNtLOwMrvVOrXJll7Gqnd2PiE+J2ENGGXQxu7PBIWF/r7y7sCcUE4DcPU+9dRqn92McEgR2839FBd5Zrn89XYtJCSgMouNg6tHuxTZ/PVwWG2y2G+7nfUBZTEUZEYYbDLuly03WIUMJCr2U5A37BKUgMj/TOhR939rBr1WlMzPJF1MFfInnEFK6iJ2zo4m/mgQdE54GshqjsneK7PeLXWtfd5m0IA56FSEsvL4TM2qhK3sg/asNDJ4SWXqQJPXd3nL1KjDZPdwecpf3QJ62Urnlfo9wBsLUyhtSzUoWSG38HyAlshD1D9wxF053djq5ldN7bfHfR9bOzk0B6eKiEtJt8ZK1YJNyfk21VClHQJRi26XzE89HhTvFQpHt3R/8o3vgVGc7tbPiywDrplCG2wJGoN9eTOufCiJs7X9m/yfxucyvKoJSKfdF2tJdJIxE9ZY9qJdG93TyiloInvV50dn/O+xcyG7XPYdfMJIT/RU8rDHp2uxH5J+tXoqIprcUyToc4Rw0m6rkzFNRZqOtJmwZsI0YHLcbiHPLJHt7+oxLWBkHaskiQe9UVZIxdib7awTJkYPHw9AUf2OrJQeyB9GAT1YdveIOKNcIPDzml20eurxWPAddXZ37q0=
dd:
  secure: BHPReemdzx3XYiUnK/3J0ZpeJSYyjt2f+PiHlkDdagJAhOs2rDjSLuW49yqZLkQwpcwMLAER4u7lqIrFFhXGMIMfnaqSNtx9KnaMtH1X7WK6F3mgqnt0KyZ99FzC/4WCpBQlYKtEjzaakcZaR/ipF4CTrHo8L5qKq5uNYD8oaMoB7UT1F26oXwNkCS2nTJC8d39dV+wYiGL1czK+F6q4H6w01BuALIfzfis/f2/jAlv8Nr42tbcjSg/jlT38msJDP5w8l5Ik2hbo8LUro7W2R+TM/BLv+WcAr1FOvF2JMgkQjEWo6RGiFed+axqbGGjK7iLO/yLupPJlHwMdV1NqGWvBO6fgky7jy8iUPCjS6GKqae378gmxVNxvMzB889aazZq86jCEachuBpjW2GyW9Usp/J+ro36H7dDOeqfc3aHz2dyLEjs6VN3hLrx77r2/4oP+BP22pP8hLwhlDYPlC8z2ou8tY8lNXiqFYvL3b/9l4v8UY/ptl5Q59yFOJawtKom4aJh2cwC3YLXSox3wWx1nDFck+msT4FU2FGHp+vn8GenOx1tgIvDIX1EhFMqokY/vT3/W+4pPpmlQwKVHU5dCM+X3tC6h/DOQd/SbJqRVrsoqOp0Uv9dK5Icczh7BFItehLKl1ho0Zl6LD1bkHyccBkS43gP9otPUFxn/G+4=
