language: node_js
node_js: lts/*
cache:
  npm: false
before_script: 
script:
- yarn install
- yarn build
deploy:
  local_dir: ".vuepress/dist/"
  provider: pages
  skip_cleanup: true
  name: Travis Build Bot
  keep_history: true
  on:
    branch: master
  target_branch: gh-pages
  github_token:
    secure: Z4TmZVZQwEzM90x1jEi8buy58rjsfZ389ag8gI0LpeeR2EkBDlz0GYFKVmEvFM0S8JfGlHpkqGbs+ktzCBBJBYl/8qVooJuxVGmcM+bidEeICWWe0YZXgzd6kaN4/JX9P6/vP3pfxYRc38iE18qMBORds1cAOHwdi1Qw7DkogpuUYMskxTQobn8I27d5ch8H7gL7CWBdcknlCaQPS04x6G/Q5MwIsyEIfDFuhodiiPj10W1gm8aS3i5z+ST7VNJRNlTgRjRkaNbn953FyZm9AJCzzmll5he24EHVJIf38UB5vVlQ/3Yy4yOI72GhUw8gzUsPHPtLFwvg3P4QaDFYOjFjv/zdya+kF9R5/OMz0QDEpft5JAJtHuAjDwcZkPrEkt7toL9pEM7KXfMXthhONXzPKPcSCQ1TNHAIu9djWHWE72T8/XIJYgbCjYwDD96hmXkatYk323lV+VMszxCmQS/If7Rp++77HZncb7xZo0fALvClsXYnzCvITnnqvSU4EXAYPAuKZeoqcjeST6uKuh0ONwCWbU2vCyCDhnU/lUzVMQ12cYX1d/iEcmof2uXyvKTfBD/nKmRBJpjWRnqmxf7lJ9EXQtbTt+yLEMgCcfYlcerLB4ulx189Jc4CeL+i7jlMYKFNaynOqGqvMz92UEixE3ZYLuzwUL80l5KnERM=
dd:
  secure: BHPReemdzx3XYiUnK/3J0ZpeJSYyjt2f+PiHlkDdagJAhOs2rDjSLuW49yqZLkQwpcwMLAER4u7lqIrFFhXGMIMfnaqSNtx9KnaMtH1X7WK6F3mgqnt0KyZ99FzC/4WCpBQlYKtEjzaakcZaR/ipF4CTrHo8L5qKq5uNYD8oaMoB7UT1F26oXwNkCS2nTJC8d39dV+wYiGL1czK+F6q4H6w01BuALIfzfis/f2/jAlv8Nr42tbcjSg/jlT38msJDP5w8l5Ik2hbo8LUro7W2R+TM/BLv+WcAr1FOvF2JMgkQjEWo6RGiFed+axqbGGjK7iLO/yLupPJlHwMdV1NqGWvBO6fgky7jy8iUPCjS6GKqae378gmxVNxvMzB889aazZq86jCEachuBpjW2GyW9Usp/J+ro36H7dDOeqfc3aHz2dyLEjs6VN3hLrx77r2/4oP+BP22pP8hLwhlDYPlC8z2ou8tY8lNXiqFYvL3b/9l4v8UY/ptl5Q59yFOJawtKom4aJh2cwC3YLXSox3wWx1nDFck+msT4FU2FGHp+vn8GenOx1tgIvDIX1EhFMqokY/vT3/W+4pPpmlQwKVHU5dCM+X3tC6h/DOQd/SbJqRVrsoqOp0Uv9dK5Icczh7BFItehLKl1ho0Zl6LD1bkHyccBkS43gP9otPUFxn/G+4=
